### ISSUE TITLE
Polling errors

### ISSUE THREAD

**Issue by tfreedman** [matrix-hacks/matrix-puppet-skype#10]
I have a bunch of these in the Skype Protocol window::

{ poll: An error happened while processing the polled messages
  caused by Error: read ECONNRESET
    at exports._errnoException (util.js:1024:11)
    at TLSWrap.onread (net.js:610:25)
  name: 'poll',
  [_message]: 'An error happened while processing the polled messages',
  data: {},
  cause: 
   { Error: read ECONNRESET
       at exports._errnoException (util.js:1024:11)
       at TLSWrap.onread (net.js:610:25)
     [stack]: 'Error: read ECONNRESET\n    at exports._errnoException (util.js:1024:11)\n    at TLSWrap.onread (net.js:610:25)',
     [message]: 'read ECONNRESET',
     code: 'ECONNRESET',
     errno: 'ECONNRESET',
     syscall: 'read' },
  [_stack]: 'poll: An error happened while processing the polled messages\n  caused by Error: read ECONNRESET\n    at exports._errnoException (util.js:1024:11)\n    at TLSWrap.onread (net.js:610:25)',
  [_stackContainer]: undefined,
  message: 'poll: An error happened while processing the polled messages\n  caused by Error: read ECONNRESET\n    at exports._errnoException (util.js:1024:11)\n    at TLSWrap.onread (net.js:610:25)' } ﻿

**Comment by Sorunome** [comment]
This is maybe related to https://github.com/ocilo/skype-http/issues/51

**Comment by nr23730** [comment]
Fixed with #28
